### ISSUE TITLE
Can you add a readme/our MIT copyright to specify that the code base comes from this repository

### ISSUE THREAD

**Issue by MightyCode** [WiFuchs/gdmc_2022_submission#13]
Can you add the names of the contributors of this source project too, it could be cool !:
MightyCode, Harckyl, YusufSenel
[Source repository](https://github.com/MightyCode/GDMC2021Tsukuba) 
[The MIT licence](https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt) 
"The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software."

(I'm writing this because you didn't fork our project to work on your own)

Thank you in advance !

**Comment by KamenShah** [comment]
Hi!
Thanks for leaving a note! We will attribute your work in our readme that we will publish soon!

**Comment by MightyCode** [comment]
Thanks you and good luck for your submission !
